spring:
  application:
    name: loans
  config:
    import: optional:configserver:http://localhost:9092/

  profiles:
    active: default

eureka:
  instance:
    prefer-ip-address: true
  client:
    fetchRegistry: true
    registerWithEureka: true
    serviceUrl:
      defaultZone: http://localhost:9093/eureka/

management:
  endpoints:
    web:
      exposure:
        include: "*"
  info:
    env:
      enabled: true
  endpoint:
    shutdown:
      access: unrestricted

info:
  app:
    name: "loans"
    description: "Coding Bank loans Applications"
    version: 1.0.0