spring:
  application:
    name: loans
  config:
    import: optional:configserver:http://localhost:9092/

  profiles:
    active: default

eureka:
  instance:
    preferIpAddress: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:9093/eureka/

management:
  endpoints:
    web:
      exposure:
        include: "*"
  info:
    env:
      enabled: true
  health:
    readiness-state:
      enabled: true
    liveness-state:
      enabled: true
  endpoint:
    shutdown:
      access: unrestricted
    health:
      probes:
        enabled: true
  metrics:
    tags:
      application: ${spring.application.name}

info:
  app:
    name: "loans"
    description: "Coding Bank loans Applications"
    version: 1.0.0

logging:
  level:
    com:
      coding:
        loans: DEBUG